### ISSUE TITLE
API call to /conversations/{id:[0-9]+}/lastcomment responding with first comment

### ISSUE THREAD

**Issue by hblackett** [microcosm-cc/microcosm#31]
Using the `lastcomment` and `newcomment` endpoints (e.g. the pattern `/api/v1/conversations/{id:[0-9]+}/newcomment`) both respond with the first page of comments (comments 1-25). Is that expected behaviour? Am I misunderstanding 'the last comment in the conversation' when I expect that to be the most recent comment?

If I want to get the most recent comments in a conversation is the recommended pattern a two-part call: first get the `data.comments.maxOffset`, then use that value in a second call `/api/v1/conversations/{id:[0-9]+}?offset={data.comments.maxOffset}`?

**Comment by buro9** [comment]
Are you passing in an authorisation context (an access_token header or query arg)? `/newcomment` needs a session and looks up the last read thing for that user.

**Comment by buro9** [comment]
Specifically when an authenticated user accesses a page of comments, the knowledge that this has occurred is stored in the `read` table if it is greater than the last value in the `read` table for that item (conversation).

The `/newcomment` endpoint uses that knowledge to go to a page of comments on which the first unread comment exists, and `read` is updated accordingly.

But that requires an authenticated session, as `read` status for guests is not recorded.

**Comment by hblackett** [comment]
I wasn't passing any auth context – thanks for clearing up, all looks good.
